### ISSUE TITLE
hello

### ISSUE THREAD

**Issue by em67re** [Modularr/Flexible-PHP-Pagination#16]
Hello i am getting mysql error when current page is -1 what do i need to do for this

**Comment by Blaxus** [comment]
@em67re Don't run the query if it's `-1`
But then it won't show anything. Do something along the lines of this:

    $page = ($_GET['page'] > 1) ? $_GET['page'] : 1;

Then just use `$page` instead of `$_GET['page']`

That should prevent the error and _**show the first page instead**_
