### ISSUE TITLE
PHP 8.2 compability fails by usage of dynamic properties

### ISSUE THREAD

**Issue by digifa** [Modularr/Flexible-PHP-Pagination#4]
PHP 8.2 compability fails by usage of dynamic properties

There are two forks solving this problem (nearly identicaly) and I created a PR for one of the forks: #3 

The other fork is by @atharalipk - and solves the same problem.

**Comment by ISTPdev** [comment]
Sorry for the delay. I must have cleared the notification and forgot.
Feel free to report any issues. I'm always happy to merge fixes that maintain compatibility.
